//! EMF record type constants.

/// `EMR_HEADER`
pub const EMR_HEADER: u32 = 1;
/// `EMR_EOF`
pub const EMR_EOF: u32 = 14;
/// `EMR_SETMAPMODE`
pub const EMR_SETMAPMODE: u32 = 17;
/// `EMR_MOVETOEX`
pub const EMR_MOVETOEX: u32 = 27;
/// `EMR_SELECTOBJECT`
pub const EMR_SELECTOBJECT: u32 = 37;
/// `EMR_CREATEPEN`
pub const EMR_CREATEPEN: u32 = 38;
/// `EMR_RECTANGLE`
pub const EMR_RECTANGLE: u32 = 42;
/// `EMR_LINETO`
pub const EMR_LINETO: u32 = 54;
/// `EMR_POLYLINE`
pub const EMR_POLYLINE: u32 = 4;
/// `EMR_POLYGON`
pub const EMR_POLYGON: u32 = 5;
/// `EMR_EXTTEXTOUTA`
pub const EMR_EXTTEXTOUTA: u32 = 83;
/// `EMR_EXTTEXTOUTW`
pub const EMR_EXTTEXTOUTW: u32 = 84;
/// `EMR_POLYGON16`
pub const EMR_POLYGON16: u32 = 86;
/// `EMR_POLYLINE16`
pub const EMR_POLYLINE16: u32 = 87;
/// `EMR_SETWORLDTRANSFORM`
pub const EMR_SETWORLDTRANSFORM: u32 = 35;
/// `EMR_MODIFYWORLDTRANSFORM`
pub const EMR_MODIFYWORLDTRANSFORM: u32 = 36;
/// `EMR_ARC`
pub const EMR_ARC: u32 = 45;
/// `EMR_CHORD`
pub const EMR_CHORD: u32 = 46;
/// `EMR_PIE`
pub const EMR_PIE: u32 = 47;
/// `EMR_ARCTO`
pub const EMR_ARCTO: u32 = 55;
/// `EMR_ELLIPSE`
pub const EMR_ELLIPSE: u32 = 49;
/// `EMR_EXTCREATEFONTINDIRECTW`
pub const EMR_EXTCREATEFONTINDIRECTW: u32 = 82;
/// `EMR_POLYBEZIER16`
pub const EMR_POLYBEZIER16: u32 = 88;
/// `EMR_EXTCREATEPEN`
pub const EMR_EXTCREATEPEN: u32 = 95;
/// `EMR_INTERSECTCLIPRECT`
pub const EMR_INTERSECTCLIPRECT: u32 = 30;
/// `EMR_EXCLUDECLIPRECT`
pub const EMR_EXCLUDECLIPRECT: u32 = 31;
/// `EMR_CREATEBRUSH`
pub const EMR_CREATEBRUSH: u32 = 39;
/// `EMR_BITBLT`
pub const EMR_BITBLT: u32 = 76;
/// `EMR_STRETCHDIBITS`
pub const EMR_STRETCHDIBITS: u32 = 81;
